### ISSUE TITLE
Weekly Opponents?

### ISSUE THREAD

**Issue by gkotas** [hvpkod/NFL-Data#1]
Really appreciate you doing this.

Is it possible to add a column to each player's row for the opponent they played?

**Comment by hvpkod** [comment]
> Really appreciate you doing this.
> 
> Is it possible to add a column to each player's row for the opponent they played?

Yes, that would be easy to add for the weekly games. Would you have any use for that?

**Comment by hvpkod** [comment]
> Really appreciate you doing this.
> 
> Is it possible to add a column to each player's row for the opponent they played?

Added PlayerOpponent for 2021.
